### ISSUE TITLE
Good Job! You've found my bot token

### ISSUE THREAD

**Issue by workspace0editor** [BRS-Reverse/fuck-you-rats#1]
Well, uhm you found my bot token so good job. Hope you have a great day. The only reason I was notify about this was because of discord and well I've decided to best move away from these kinds of stuff and raid other skidders to repay for my actions.
![Screenshot (112)](https://github.com/user-attachments/assets/f77a0b43-b117-4de3-8b6e-e181041e7311)

**Comment by workspace0editor** [comment]
No harsh feelings right?

**Comment by ReverseBRS** [comment]
No harsh feeling. please stop ratting people in the future.

Best,
-BRS
