### ISSUE TITLE
can i get in contact with you?

### ISSUE THREAD

**Issue by 0xBenCantCode** [BRS-Reverse/fuck-you-rats#2]
im working on automating sifting through malicious github repositories for tokens, webhooks, and other junk. its cool to find a like-minded person and i would like to maybe work with you!

shoot me a message on discord @portswigger

**Comment by 0xBenCantCode** [comment]
note - im not portswigger (duh) just a cool name i got

**Comment by ReverseBRS** [comment]
Added.
